version: "3"

services:
    testing:
        build:
            context: .
            dockerfile: Dockerfile.CI
        command:
            [
                "pytest",
                "-n",
                "auto",
                "--cov=.",
                "--cov-report=xml:/app/coverage/coverage.xml",
                "--cov-report=term-missing",
            ]
        env_file:
            - .cv_deploy.env
        volumes:
            - documents:/app/documents
            - cv_model:/app/cv_model
