# main.py

import logging
import os
import subprocess
import sys
from fastapi import FastAPI, Request, HTTPException, Depends
from fastapi.responses import JSONResponse
from fastapi.middleware.cors import CORSMiddleware
from app.apis import main_router  # Ensure this path is correct based on your project structure
from app.database import database  # Adjust the import based on your project structure
from app.apis.main_router import sanitize_error_message  # Import the sanitize function

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Initialize the FastAPI app
app = FastAPI(
    title="Map Action API",
    description="API for Map Action classification and chat functionalities.",
    version="1.0.0",
)

# CORS middleware configuration
# Adjust `allow_origins` to specify the exact origins allowed in production for better security
app.add_middleware(
    CORSMiddleware,
    allow_origins=["https://app.map-action.com", "https://www.map-action.com", "http://localhost", "http://localhost:3000"],  # Replace "*" with specific origins like ["https://yourdomain.com"] in production
    allow_credentials=True,
    allow_methods=["*"],  # Allow all HTTP methods; restrict if necessary
    allow_headers=["*"],  # Allow all headers; restrict if necessary
)

# Custom exception handler to sanitize error messages
@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException):
    """
    Handles HTTPExceptions by sanitizing error messages to avoid leaking sensitive information.

    Args:
        request (Request): The incoming request.
        exc (HTTPException): The exception instance.

    Returns:
        JSONResponse: A JSON response with the sanitized error detail.
    """
    # Retrieve sensitive structures from request state if available
    sensitive_structures = getattr(request.state, 'sensitive_structures', [])
    sanitized_detail = sanitize_error_message(str(exc.detail), sensitive_structures)
    return JSONResponse(
        status_code=exc.status_code,
        content={"detail": sanitized_detail},
    )

# Middleware to log all incoming requests and outgoing responses
@app.middleware("http")
async def log_requests(request: Request, call_next):
    """
    Logs each incoming request and its corresponding response.

    Args:
        request (Request): The incoming HTTP request.
        call_next (Callable): The next middleware or endpoint handler.

    Returns:
        Response: The HTTP response generated by the endpoint.
    """
    logger.info(f"Received request: {request.method} {request.url}")
    try:
        response = await call_next(request)
    except Exception as e:
        logger.error(f"Error processing request: {e}")
        raise e
    logger.info(f"Finished processing: {request.method} {request.url} - Status: {response.status_code}")
    return response

# Event handler for application startup
@app.on_event("startup")
async def startup():
    """
    Handles tasks to be performed on application startup, such as connecting to the database.
    """
    logger.info("Starting up the Map Action API...")
    try:
        await database.connect()
        logger.info("Connected to the database successfully.")
    except Exception as e:
        logger.error(f"Failed to connect to the database: {e}")
        raise e

# Event handler for application shutdown
@app.on_event("shutdown")
async def shutdown():
    """
    Handles tasks to be performed on application shutdown, such as disconnecting from the database.
    """
    logger.info("Shutting down the Map Action API...")
    try:
        await database.disconnect()
        logger.info("Disconnected from the database successfully.")
    except Exception as e:
        logger.error(f"Failed to disconnect from the database: {e}")
        raise e

# Include the main_router without a prefix to keep routes as defined in main_router.py
app.include_router(main_router.router, prefix="/api1")

# Root endpoint to verify API is running
@app.get("/")
async def root():
    """
    Root endpoint that returns a welcome message.

    Returns:
        dict: A simple welcome message.
    """
    return {"message": "Welcome to the Map Action API"}

# Health check endpoint to verify application health
@app.get("/health")
async def health_check():
    """
    Health check endpoint to verify that the API is operational.

    Returns:
        dict: A status message indicating health.
    """
    return {"status": "healthy"}

@app.on_event("startup")
async def startup_event():
    """
    Runs when the application starts.
    Install additional dependencies if needed and setup directories.
    """
    logging.info("Starting application setup...")
    
    # Create required directories
    os.makedirs("cv_model", exist_ok=True)
    os.makedirs("local_uploads", exist_ok=True)
    
    # Show environment information for debugging
    logging.info(f"Python version: {sys.version}")
    logging.info(f"Current working directory: {os.getcwd()}")
    logging.info(f"Environment variables: {', '.join(f'{k}' for k in os.environ.keys())}")
    
    # Check if we need to install additional packages
    if os.environ.get("INSTALL_ADDITIONAL_PACKAGES", "").lower() == "true":
        logging.info("Installing additional packages...")
        
        # First tier - packages that are likely to work without system dependencies
        simple_packages = [
            "redis",
            "pillow",
            "python-dotenv",
            "openai"
        ]
        
        # Second tier - packages that might need system dependencies but are important
        tier2_packages = [
            "databases",
            "asyncpg",
            "matplotlib"
        ]
        
        # Third tier - packages that definitely need system dependencies
        complex_packages = [
            "psycopg2-binary",
            "earthengine-api",
            "shapely",
            "langchain==0.1.5",
            "langchain-community==0.0.18"
        ]
        
        # Very complex packages - often fail on restricted environments
        very_complex_packages = [
            "scipy",
            "rasterio",
            "geopandas",
            "azure-storage-blob",
            "azure-identity"
        ]
        
        # Function to safely install packages
        def install_packages(package_list, tier_name):
            success_count = 0
            for pkg in package_list:
                try:
                    logging.info(f"Installing {pkg}...")
                    subprocess.check_call([
                        sys.executable, "-m", "pip", "install", "--no-cache-dir", pkg
                    ])
                    success_count += 1
                except Exception as e:
                    logging.warning(f"Failed to install {pkg}: {str(e)}")
            
            return success_count
        
        # Install packages in order of complexity
        simple_success = install_packages(simple_packages, "basic")
        logging.info(f"Successfully installed {simple_success}/{len(simple_packages)} basic packages")
        
        tier2_success = install_packages(tier2_packages, "tier2")
        logging.info(f"Successfully installed {tier2_success}/{len(tier2_packages)} tier 2 packages")
        
        # Only try complex packages if we had success with simpler ones
        if tier2_success > 0:
            complex_success = install_packages(complex_packages, "complex")
            logging.info(f"Successfully installed {complex_success}/{len(complex_packages)} complex packages")
            
            # Only try very complex packages if at least some complex ones worked
            if complex_success > 0:
                very_complex_success = install_packages(very_complex_packages, "very complex")
                logging.info(f"Successfully installed {very_complex_success}/{len(very_complex_packages)} very complex packages")
    
    logging.info("Application setup complete")

# If running this file directly, start the Uvicorn server
if __name__ == "__main__":
    import uvicorn

    # Configure Uvicorn settings as needed
    uvicorn.run(
        "main:app",  # Module and app instance
        host="0.0.0.0",  # Listen on all interfaces
        port=8000,       # Port number
        reload=True,
        ws="websockets",     # Enable auto-reload for development
        log_level="info",# Set log level
    )