# # .github/workflows/docs_deploy.yml

# name: Deploy MkDocs Site

# on:
#     push:
#         branches:
#             - main

# permissions:
#     contents: write
#     pages: write
#     id-token: write

# jobs:
#     deploy-docs:
#         runs-on: ubuntu-latest # You can switch to self-hosted if preferred

#         steps:
#             - name: Checkout Repository
#               uses: actions/checkout@v3

#             - name: Set up Python
#               uses: actions/setup-python@v3
#               with:
#                   python-version: "3.10" # Specify your required Python version

#             - name: Install Dependencies
#               run: |
#                   pip install mkdocs mkdocstrings mkdocs-material mkdocstrings-python

#             - name: Build MkDocs Site
#               run: mkdocs build

#             - name: Configure Git
#               run: |
#                   git config user.name "github-actions[bot]"
#                   git config user.email "github-actions[bot]@users.noreply.github.com"

#             - name: Deploy to GitHub Pages
#               uses: peaceiris/actions-gh-pages@v4 # Ensure this is the latest stable version
#               with:
#                   github_token: ${{ secrets.GITHUB_TOKEN }} # Use the built-in GITHUB_TOKEN
#                   publish_dir: ./site
